{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-{{ include "helm-backend.fullname" . }}
type: Opaque
data:
  username: {{ .Values.data.username }}
  password: {{ .Values.data.password }}
  db-host: {{ .Values.data.dbhost }}
  {{- end }}


