apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJNb2hzaW5IYXNobWktRGF0YUlubiIsInBhc3N3b3JkIjoiZ2hwXzNJSjBKODNSV04zMERxckc4STNRQnFac2VpVmNyRzA1NFJpTCIsImVtYWlsIjoibW9oc2luQGRhdGFpbm4uaW8iLCJhdXRoIjoiVFc5b2MybHVTR0Z6YUcxcExVUmhkR0ZKYm00NloyaHdYek5KU2pCS09ETlNWMDR6TUVSeGNrYzRTVE5SUW5GYWMyVnBWbU55UnpBMU5GSnBUQT09In19fQ==
kind: Secret
metadata:
  name: github-package-secret
type: kubernetes.io/dockerconfigjson
