apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-backend.fullname" . }}

  labels:
    {{- include "helm-backend.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.ports.containerPort.backendPort }}
  selector:
    {{- include "helm-backend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
